// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(FormJS) {
    /*
    	Type: select
    	Notes: A dropdown <select> element
    	Options:
    		_options: a hashmap of value and labels
    		_multiple: boolean wether the "multiple" attribute should be set
    */
    return FormJS.registerType('select', function(options) {
      var label, opt, tag, val, _ref;
      if (options._multiple && (options._multiple === !!options._multiple)) {
        options._multiple = 'multiple';
      } else {
        delete options._multiple;
      }
      tag = jQuery('<select />');
      _ref = options._options;
      for (val in _ref) {
        label = _ref[val];
        opt = jQuery('<option />').attr('value', val).html(label);
        if (val === options._value) {
          opt.attr('selected', 'selected');
        }
        opt.appendTo(tag);
      }
      return this.applyAttributes(tag, options);
    });
  };

}).call(this);
